[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.0", features = ["derive"] }
itertools = "0.13"
hashbrown = "0.15"
regex = "1.11"
once_cell = "1.14.0"